language: python
sudo: required

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty"
    # May 2017: Xenial support in travis broken (prcise image is booted)
    #- dist: xenial
    #  env: dist="16.04 LTS xenial"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev
  #- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #- sudo apt-get -qq update 

install:
  - cd ansible; sudo ansible-playbook -i "localhost," -c local -v install.yml; cd ..

script:
  - sudo py.test -v mininet/test/test_containernet.py

notifications:
  email:
    on_success: change
    on_failure: always
