- hosts: localhost
  tasks:
   - name: updates apt
     apt: update_cache=yes

   - name: upgrade apt
     apt: upgrade=full

   - name: install curl
     apt: pkg=curl state=installed

   - name: install pip
     apt: pkg=python-pip state=installed

   - name: ensure docker repo key
     shell: curl -fsSL https://get.docker.com/gpg | apt-key add -

   - name: install docker
     shell: curl -fsSL https://get.docker.com/ | sh

   - name: install setuptools
     pip: name=setuptools state=latest

   - name: install docker-py
     pip: name=docker-py state=latest

   - name: built and install Conatinernet (using Mininet installer)
     shell: containernet/util/install.sh
     args:
       chdir: ../../

   - name: install Conatinernet Python egg et.c
     shell: make develop
     args:
       chdir: ../

   - name: download 'ubuntu' docker image for Conatinernet example
     shell: docker run ubuntu:trusty