name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests on Ubuntu 18.04

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: |
        sudo apt-get -y install ansible vlan 
        cd ansible
        sudo ansible-playbook -i "localhost," -c local install.yml
    - name: Run Tests
      run: |
        sudo pytest -v mininet/test

  test-on-ubuntu:
    name: Run tests in Ubuntu 18.04 container

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    # OVS needs to install a kernel module. We do not want to allow
    # the container to modify the kernel so we install it before.
    - name: Install OVS
      run: |
        sudo apt-get -y install openvswitch-switch
    - name: Build container
      run: |
        docker build -t containernet/containernet:ubuntu -f ./Dockerfile .
    - name: Run tests in container
      run: |
        docker run --name containernet -i --rm --privileged \
          --pid='host' \
          -v /var/run/docker.sock:/var/run/docker.sock \
          containernet/containernet:ubuntu \
          py.test -v mininet/test/

  test-on-centos:
    name: Run tests in CentOS 7 container

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    # OVS needs to install a kernel module. We do not want to allow
    # the container to modify the kernel so we install it before.
    - name: Install OVS
      run: |
        sudo apt-get -y install openvswitch-switch
    - name: Build container
      run: |
        docker build -t containernet/containernet:centos7 -f ./Dockerfile.centos .
    - name: Run tests in container
      run: |
        docker run --name containernet -i --rm --privileged \
          --pid='host' \
          -v /var/run/docker.sock:/var/run/docker.sock \
          containernet/containernet:centos7 \
          py.test -v mininet/test/
